/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as ActivitiesCreateRouteImport } from './routes/activities/create'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities/$activityId'
import { Route as ActivityActivityIdIndexRouteImport } from './routes/activity/$activityId/index'
import { Route as ActivityActivityIdUpdateRouteImport } from './routes/activity/$activityId/update'
import { Route as ActivityActivityIdRecordsCreateRouteImport } from './routes/activity/$activityId/records/create'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesCreateRoute = ActivitiesCreateRouteImport.update({
  id: '/activities/create',
  path: '/activities/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityActivityIdIndexRoute = ActivityActivityIdIndexRouteImport.update({
  id: '/activity/$activityId/',
  path: '/activity/$activityId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityActivityIdUpdateRoute =
  ActivityActivityIdUpdateRouteImport.update({
    id: '/activity/$activityId/update',
    path: '/activity/$activityId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActivityActivityIdRecordsCreateRoute =
  ActivityActivityIdRecordsCreateRouteImport.update({
    id: '/activity/$activityId/records/create',
    path: '/activity/$activityId/records/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/create': typeof ActivitiesCreateRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/activity/$activityId/update': typeof ActivityActivityIdUpdateRoute
  '/activity/$activityId/': typeof ActivityActivityIdIndexRoute
  '/activity/$activityId/records/create': typeof ActivityActivityIdRecordsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/create': typeof ActivitiesCreateRoute
  '/activities': typeof ActivitiesIndexRoute
  '/activity/$activityId/update': typeof ActivityActivityIdUpdateRoute
  '/activity/$activityId': typeof ActivityActivityIdIndexRoute
  '/activity/$activityId/records/create': typeof ActivityActivityIdRecordsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/create': typeof ActivitiesCreateRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/activity/$activityId/update': typeof ActivityActivityIdUpdateRoute
  '/activity/$activityId/': typeof ActivityActivityIdIndexRoute
  '/activity/$activityId/records/create': typeof ActivityActivityIdRecordsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities/$activityId'
    | '/activities/create'
    | '/activities/'
    | '/activity/$activityId/update'
    | '/activity/$activityId/'
    | '/activity/$activityId/records/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities/$activityId'
    | '/activities/create'
    | '/activities'
    | '/activity/$activityId/update'
    | '/activity/$activityId'
    | '/activity/$activityId/records/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities/$activityId'
    | '/activities/create'
    | '/activities/'
    | '/activity/$activityId/update'
    | '/activity/$activityId/'
    | '/activity/$activityId/records/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  ActivitiesCreateRoute: typeof ActivitiesCreateRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ActivityActivityIdUpdateRoute: typeof ActivityActivityIdUpdateRoute
  ActivityActivityIdIndexRoute: typeof ActivityActivityIdIndexRoute
  ActivityActivityIdRecordsCreateRoute: typeof ActivityActivityIdRecordsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/create': {
      id: '/activities/create'
      path: '/activities/create'
      fullPath: '/activities/create'
      preLoaderRoute: typeof ActivitiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$activityId/': {
      id: '/activity/$activityId/'
      path: '/activity/$activityId'
      fullPath: '/activity/$activityId/'
      preLoaderRoute: typeof ActivityActivityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$activityId/update': {
      id: '/activity/$activityId/update'
      path: '/activity/$activityId/update'
      fullPath: '/activity/$activityId/update'
      preLoaderRoute: typeof ActivityActivityIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$activityId/records/create': {
      id: '/activity/$activityId/records/create'
      path: '/activity/$activityId/records/create'
      fullPath: '/activity/$activityId/records/create'
      preLoaderRoute: typeof ActivityActivityIdRecordsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  ActivitiesCreateRoute: ActivitiesCreateRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ActivityActivityIdUpdateRoute: ActivityActivityIdUpdateRoute,
  ActivityActivityIdIndexRoute: ActivityActivityIdIndexRoute,
  ActivityActivityIdRecordsCreateRoute: ActivityActivityIdRecordsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
